packages:
  - "."

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  postcss@<8.5.10: '>=8.5.10'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'
  seroval@>=0.2.0 <=1.4.0: '>=1.4.1'
  vite@<=6.4.1: '>=6.4.2'
